name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test run
        run: cargo run
